name: dotnet format

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cs'

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run dotnet format
        run: dotnet format server.csproj --no-restore --verify-no-changes
